Battery ADC Change
StudentOrganisationForAerospaceResearch/AvionicsSoftware pull request #37
Opened 2021-12-04 20:54 UTC by Abhay2412

For reading battery voltage and adding the thread to the AllData file.

2021-12-11 20:53 UTC, Matt4890 requested changes, later dismissed
Needs some testing and some tiny details, but looks good!

2021-12-11 20:53 UTC, Matt4890 commented on Inc/Data.h
> +    uint32_t     voltage_;
Nit: Extra space

2021-12-11 20:53 UTC, Matt4890 commented on Inc/Data.h
> +    uint32_t     voltage_;
What units are we storing `voltage_` as? If undecided, I would suggest mV. This way, we can use an `int16_t` and store a value anywhere from -32.768V to 32.767V, which I think is a reasonable range. I don't think we need a full `uint32_t` for storing voltage lol.

2021-12-11 20:53 UTC, Matt4890 commented on Src/ReadBatteryVoltage.c
> +static int READ_BATTERY_VOLTAGE_PERIOD = 250;
This could probably be increased to 1000 or more. I don't think we need to be sampling battery voltage that often.

2021-12-11 20:53 UTC, Matt4890 commented on Src/ReadBatteryVoltage.c
> +    double batteryVoltageValue = 0; //Not quite sure if it's a double or int can confirm
`uint32_t HAL_ADC_GetValue(ADC_HandleTypeDef* hadc)`
The `HAL_ADC_GetValue` function returns a uin32_t. We're gonna need to research/test to figure out how to scale it to mV. (i.e. is the returned value in volts? or 0x00000000 to 0xFFFFFFFF based off of 0V-5V? etc)

2022-01-08 18:32 UTC, Abhay2412 commented on Inc/Data.h
> +    uint32_t     voltage_;
Fixed this space.

2022-05-09 18:25 UTC, Matt4890 commented on Inc/Data.h
> +    uint32_t     voltage_;
Changing this to an `int16_t` and declaring the unit as millivolts.

2022-05-09 18:25 UTC, Matt4890 commented on Src/ReadBatteryVoltage.c
> +static int READ_BATTERY_VOLTAGE_PERIOD = 250;
Increasing to 1000.

2022-05-09 18:41 UTC, Matt4890 commented
We should test the ADC read output before merging. Will do later, maybe on a dev board.

2022-06-02 17:12 UTC, merged