Jesse/rocket control functionality
StudentOrganisationForAerospaceResearch/AvionicsSoftware pull request #59
Opened 2023-01-28 18:00 UTC by Jgerbrandt

2023-02-01 06:06 UTC, AgamAulakh requested changes
Great job! Most of these comments are discussion points

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> +PA9.GPIO_Label=RCU_RS485_USART1_TX
hard to comment on an IOC file, but I think we should not add "RS485" to the pin names. To the STM, these are used as UART lines and firmware doesn't care if they're converted to a specific kind of differential pair comm

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> +PB1.GPIO_Label=PS1_ADC1_IN9
nitpick: I don't think we should include the specific pin type in the names. When we use the user-defined names in our code, we should be blind to, for example, the actual uart line/adc channel being used. I suggest we remove the actual pin name that's kept in the middle (like changing GPS_UART4_RX to just GPS_RX). I'm definitely open to discussion on this point!

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> +PB1.GPIO_Label=PS1_ADC1_IN9
Although the schematic has this as "PS1," I think we should just call it AV_Pressure or something along those lines

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> +PA1.GPIO_Label=GPS_UART4_RX
Note to Chris: GPS uart has been configured to use DMA (GPS --> mcu memory)

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> -PA8.GPIO_Label=LAUNCH
We should configure the gpio _input_ pins (LAUNCH and DMB_ABORT) to be _pulled down_

2023-02-01 06:06 UTC, AgamAulakh commented on AvionicsSoftware.ioc
> -PA8.GPIO_Label=LAUNCH
AUX_2 should be pull up. Though we don't currently use this pin, in the past we have used the auxiliary pins for debugging by holding them to ground.

2023-02-01 06:06 UTC, AgamAulakh commented on Components/FlightControl/RocketSM.cpp
>          return RS_ABORT;
This doesn't have to be included in this PR, but we should think about making the LAUNCH and DMB_ABORT input pins trigger an interrupt in order to immediately queue the right state transition command.

2023-02-01 06:06 UTC, AgamAulakh commented on Components/FlightControl/RocketSM.cpp
>              // Transition to ready for ignition state
Got some more clarification on the ignition state transitions from Mo:
As soon as we enter the ignition state, we should start a timer for the igniter delay. If the timer expires before the launch command is received, we should go into Arm. If the launch command is received, we should wait until the timer expires before entering launch and opening the MEV

2023-02-04 23:54 UTC, cjchanx requested changes
Last commit has modified alot of files unintended, likely due to autocrlf and Macs leaving a .DS_Store file.

Run `git config --global core.autocrlf true` on any Windows desktops to keep consistent line endings.

2023-03-28 04:11 UTC, cjchanx commented on Components/FlightControl/Inc/RocketSM.hpp
> +
Remove these two lines

2023-06-10 19:46 UTC, cjchanx commented on Core/.DS_Store
Remove :)

2023-06-10 19:47 UTC, cjchanx commented on Components/FlightControl/TelemetryTask.cpp
>      //TODO: Commented out for now, until merged with the flight task changes
Call this function in RunLogSequence

2023-06-10 21:53 UTC, cjchanx approved these changes

2023-06-10 22:17 UTC, merged